version: '3.8'
name: 'weather_collector'
services:
  db:
    image: postgres:15-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  weather_collector:
    build: ./app
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  db_data:
