version: '3.8'
name: 'weather_collector'
services:
  db:
    image: postgres:15-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 10s
      retries: 5
    env_file:
      - ./.env

  weather_collector:
    build: ./app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env

volumes:
  db_data:
